name: Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.x

      - run: pip install -e .[doc,cpu] && mkdocs gh-deploy --force
